# SPDX-FileCopyrightText: 2019 TQ Tezos <https://tqtezos.com/>
#
# SPDX-License-Identifier: MPL-2.0

env:
  NIX_PATH: nixpkgs=https://github.com/serokell/nixpkgs/archive/master.tar.gz
  cur_date: '$(date --date="$(git show --no-patch --format=%ci)" +"%Y%m%d%H%M")'

steps:
 - command: nix run nixpkgs.reuse -c reuse lint
   label: reuse lint
 - command: .buildkite/check-trailing-whitespace.sh
   label: check trailing whitespace
 - command: "nix run -f https://github.com/serokell/crossref-verifier/archive/68a1f9d25b6e7835fea8299b18a3e6c61dbb2a5c.tar.gz -c crossref-verify"
   label: crossref-verify
   soft_fail: true
 - commands:
   - nix-build -A binaries -o binaries
   - nix-build -A deb -o deb-packages --arg timestamp ${cur_date}
   - nix-build -A rpm -o rpm-packages --arg timestamp ${cur_date}
   label: build and package
   artifact_paths:
     - ./binaries/bin/*
     - ./deb-packages/*
     - ./rpm-packages/*
   branches: "!master"
 - commands:
   - nix-build -A test-binaries --no-out-link
   label: test binaries
   branches: "!master"
 - commands:
   - GITHUB_TOKEN=$(cat ~/niv-bot-token) ./scripts/autorelease.sh
   label: create auto pre-release
   branches: master
